### ISSUE TITLE
WebhookURLInvalid

### ISSUE THREAD

**Issue by ThePurpleWurmple** [wyanido/pokebot-nds#43]
I'm new to this whole PokéBot NDS thing and I tried integrating a webhook into my discord server and when I put in the right details, I try to run the test message and this is what I get:
}
Error [WebhookURLInvalid]: The provided webhook URL is not valid.
    at new WebhookClient (C:\Users\#####\Desktop\pokebot-nds-1.0.5-beta\dashboard\node_modules\discord.js\src\client\WebhookClient.js:51:15)
    at Object.webhookTest (C:\Users\#####\Desktop\pokebot-nds-1.0.5-beta\dashboard\socket.js:386:27)
    at handleAPIRequest (C:\Users\#####\Desktop\pokebot-nds-1.0.5-beta\dashboard\app.js:83:20)
    at Server.<anonymous> (C:\Users\#####\Desktop\pokebot-nds-1.0.5-beta\dashboard\app.js:21:26)
    at Server.emit (node:events:519:28)
    at parserOnIncoming (node:_http_server:1140:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
  code: 'WebhookURLInvalid'
}

Would like some help if you can! And am I giving any personal information in the error output above?

**Comment by StoryZealot** [comment]
I hope you've figured this out by now. If not, ask the discord.
